server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker
      preferredNetworks:
        - 10.0.0

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
zuul:
  routes:
    auth:
      path: /authenticate/**
      sensitiveHeaders: Cookie
      stripPrefix: false
    movie:
      path: /movies/**
      sensitiveHeaders: Set-Cookie
      stripPrefix: false
    home:
      path: /**
      sensitiveHeaders: Cookie
      stripPrefix: false
