server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users
          uri: lb://USER
          predicates:
            - Path=/users/**
        - id: movies
          uri: lb://MOVIE
          predicates:
            - Path=/movies/**
        - id: home
          uri: lb://HOME
          predicates:
            - Path=/**
