INSERT INTO food (id, name, description, image, price, type) VALUES
        (999L, 'Popcorn mini (sweet)', 'Taste the sweetest popcorn!!! Now special for the small eaters!!!', 'https://raw.githubusercontent.com/Rubinjo/cinema_microservices/main/resources/Baby_groot_with_popcorn.jpg', 2.95, 'Popcorn'),
        (998L, 'Popcorn medi (sweet)', 'Taste the sweetest popcorn!!! Now tastefully popped for all!!!', 'https://raw.githubusercontent.com/Rubinjo/cinema_microservices/main/resources/Teenage_groot_with_popcorn.jpg', 4.45, 'Popcorn'),
        (997L, 'Popcorn maxi (sweet)', 'Taste the sweetest popcorn!!! Now in extremely large bucket!!!', 'https://raw.githubusercontent.com/Rubinjo/cinema_microservices/main/resources/Groot_with_popcorn.jpg', 5.95, 'Popcorn'),
        (996L, 'Coca Cola mini', 'Stay alert to outsmart all those theorists that try to destory your movie experience!!!', 'https://target.scene7.com/is/image/Target/GUEST_0a6df736-e5ad-48ee-bda5-91e8b17021ee?wid=488&hei=488&fmt=pjpeg', 1.95, 'Drink'),
        (995L, 'Coca Cola medi', 'Stay alert to outsmart all those theorists that try to destory your movie experience!!!', 'https://target.scene7.com/is/image/Target/GUEST_0a6df736-e5ad-48ee-bda5-91e8b17021ee?wid=488&hei=488&fmt=pjpeg', 2.95, 'Drink'),
        (994L, 'Coca Cola maxi', 'Stay alert to outsmart all those theorists that try to destory your movie experience!!!', 'https://target.scene7.com/is/image/Target/GUEST_0a6df736-e5ad-48ee-bda5-91e8b17021ee?wid=488&hei=488&fmt=pjpeg', 3.95, 'Drink'),
        (993L, 'Grolsch 45cl', 'Enrich your movie experience with the amazing taste after PLOP', 'https://raw.githubusercontent.com/Rubinjo/cinema_microservices/main/resources/FatThorGrolsch.png', 3.95, 'Beer'),
        (992L, 'Grimbergen Blond', 'Grimbergen Blond for the taste sensation enthusiasts', 'https://raw.githubusercontent.com/Rubinjo/cinema_microservices/main/resources/FatThorGrimbergen.png', 4.50, 'Beer'),
        (991L, 'Tripel Karmeliet', 'Triple Karmeliet for the real diehards', 'https://raw.githubusercontent.com/Rubinjo/cinema_microservices/main/resources/FatThorKarmeliet.png', 3.95, 'Beer');